# _targets.R file
library(targets)
source("R/functions.R")
library(crew)
library(tarchetypes)

tar_option_set(packages = c("data.table", "dplyr", "ENMeval","janitor", "magrittr", "maxnet", "purrr", "Rarity", "readxl",
                            "SDMWorkflows", "stringr", "tidyr", "tibble","terra", "V.PhyloMaker", "BDRUtils"),
               controller = crew_controller_local(workers = 60),
               error = "null") # Force skip non-debugging outdated targets)
list(
  tar_target(LanduseSuitability,
             "HabSut/HabSut.tif",
             format = "file"),
  tar_target(LandUseTiff,
             "Dir/LU.tif",
             format = "file"),
  tar_target(file, "2022-09-21.xlsx", format = "file"),
  tar_target(data, get_data(file)),
  tar_target(Clean, clean_species(data)),
  tar_target(Only_Plants, filter_plants(Clean)),
  tar_target(Count_Presences,
             count_presences(Only_Plants),
             pattern = map(Only_Plants)),
  tar_target(Filter_Counts, filter_counts(Count_Presences, n = 5)),
  tar_target(Presences,
             get_plant_presences(Filter_Counts),
             pattern = map(Filter_Counts)),
  tar_target(buffer_500, make_buffer_rasterized(DT = Presences, file = LandUseTiff),
             pattern = map(Presences),
             iteration = "group"),
  tar_target(Long_Buffer, make_long_buffer(DT = buffer_500),
             pattern = map(buffer_500),
             iteration = "group"),
  tar_target(Phylo_Tree, generate_tree(Filter_Counts)),
  tar_target(ModelAndPredict, ModelAndPredictFunc(DF =  Presences, file = LandUseTiff),
             pattern = map(Presences)),
             #iteration = "group"),
  tar_target(Thresholds, create_thresholds(Model = ModelAndPredict,reference = Presences, LandUseTiff),
             pattern = map(ModelAndPredict, Presences),
             iteration = "group"),
  tar_target(LookUpTable, Generate_Lookup(Model = ModelAndPredict, Thresholds = Thresholds)),
  tar_target(LanduseTable, generate_landuse_table(path = LanduseSuitability)),
  tar_target(Long_LU_table, Make_Long_LU_table(DF = LanduseTable)),
  tar_target(Final_Presences, make_final_presences(Long_LU_table, Long_Buffer, LookUpTable),
             pattern = map(Long_Buffer),
             iteration = "group"),
  tarchetypes::tar_group_by(joint_final_presences, as.data.frame(Final_Presences), Landuse),
  tar_target(rarity_weight, calc_rarity_weight(joint_final_presences)),
  tar_target(rarity, calc_rarity(joint_final_presences, rarity_weight),
             map(joint_final_presences),
             iteration = "group"),
  tar_target(PhyloDiversity,
             calc_pd(joint_final_presences, Phylo_Tree),
             map(joint_final_presences),
             iteration = "group"),
  tar_target(Richness, GetRichness(Final_Presences)),
  tar_target(name = output_Richness,
             command = export_richness(Results = PhyloDiversity, path = LandUseTiff),
             map(PhyloDiversity),
             format = "file"),
  tar_target(name = output_PD,
             command = export_pd(Results = PhyloDiversity, path = LandUseTiff),
             map(PhyloDiversity),
             format = "file"),
  tar_target(name = output_Rarity,
             command = export_rarity(Results = rarity, path = LandUseTiff),
             map(rarity),
             format = "file")
)

